# Base16 Felinoid - wezterm color config
# Scheme by Emma Eilefsen Glenna (http://eilefsen.net)

[colors]
foreground    = "#f8f8f2"
background    = "#232629"
cursor_bg     = "#f8f8f2"
cursor_border = "#f8f8f2"
cursor_fg     = "#232629"
selection_bg  = "#474d53"
#selection_fg  = "#f8f8f2"

scrollbar_thumb = "#c9cdd1"
split           = "#626b73"
compose_cursor  = "#fba900"

#copy_mode_active_highlight_bg   = { Color = '#474d53' }
#copy_mode_active_highlight_fg   = { Color = '#f8f8f2' }
#copy_mode_inactive_highlight_bg = { Color = '#474d53' }
#copy_mode_inactive_highlight_fg = { Color = '#c9cdd1' }

#quick_select_label_bg = { Color = '#474d53)' },
#quick_select_label_fg = { Color = '#f8f8f2' },
#quick_select_match_bg = { Color = '#474d53' },
#quick_select_match_fg = { Color = '#c9cdd1' },

ansi = [
  "#232629",
  "#fb0029",
  "#00fb55",
  "#fbd300",
  "#00a6fb",
  "#fb00a6",
  "#c379e4",
  "#f8f8f2"
]

brights = [
  "#626b73",
  "#fb0029",
  "#00fb55",
  "#fbd300",
  "#00a6fb",
  "#fb00a6",
  "#c379e4",
  "#fcfcfc"
]

[colors.tab_bar]
background = "#232629"

[colors.tab_bar.active_tab]
bg_color    = "#474d53"
fg_color    = "#f8f8f2"
intensity   = "Normal"
underline   = "None"
italic      = true
strikethrough = false

[colors.tab_bar.inactive_tab]
bg_color    = "#3e4349"
fg_color    = "#c9cdd1"
intensity   = "Normal"
underline   = "None"
italic      = true
strikethrough = false

[colors.tab_bar.inactive_tab_hover]
bg_color    = "#3e4349"
fg_color    = "#f8f8f2"
intensity   = "Normal"
underline   = "None"
italic      = true
strikethrough = false

[colors.tab_bar.new_tab]
bg_color    = "#3e4349"
fg_color    = "#c9cdd1"
intensity   = "Normal"
underline   = "None"
italic      = true
strikethrough = false

[colors.tab_bar.new_tab_hover]
bg_color    = "#3e4349"
fg_color    = "#f8f8f2"
intensity   = "Normal"
underline   = "None"
italic      = true
strikethrough = false