# Base16 Felinoid - wezterm color config
# Scheme by Emma Eilefsen Glenna (http://eilefsen.net)

[colors]
foreground    = "#f6f8fa"
background    = "#292f37"
cursor_bg     = "#f6f8fa"
cursor_border = "#f6f8fa"
cursor_fg     = "#292f37"
selection_bg  = "#717b87"
#selection_fg  = "#f6f8fa"

scrollbar_thumb = "#c0c5cb"
split           = "#98a0a9"
compose_cursor  = "#fba900"

#copy_mode_active_highlight_bg   = { Color = '#717b87' }
#copy_mode_active_highlight_fg   = { Color = '#f6f8fa' }
#copy_mode_inactive_highlight_bg = { Color = '#717b87' }
#copy_mode_inactive_highlight_fg = { Color = '#c0c5cb' }

#quick_select_label_bg = { Color = '#717b87)' },
#quick_select_label_fg = { Color = '#f6f8fa' },
#quick_select_match_bg = { Color = '#717b87' },
#quick_select_match_fg = { Color = '#c0c5cb' },

ansi = [
  "#292f37",
  "#fb0029",
  "#00fb55",
  "#fbd300",
  "#00a6fb",
  "#fb00a6",
  "#c379e4",
  "#f6f8fa"
]

brights = [
  "#98a0a9",
  "#fb0029",
  "#00fb55",
  "#fbd300",
  "#00a6fb",
  "#fb00a6",
  "#c379e4",
  "#f3f5f7"
]

[colors.tab_bar]
background = "#292f37"

[colors.tab_bar.active_tab]
bg_color    = "#717b87"
fg_color    = "#f6f8fa"
intensity   = "Normal"
underline   = "None"
italic      = true
strikethrough = false

[colors.tab_bar.inactive_tab]
bg_color    = "#515a65"
fg_color    = "#c0c5cb"
intensity   = "Normal"
underline   = "None"
italic      = true
strikethrough = false

[colors.tab_bar.inactive_tab_hover]
bg_color    = "#515a65"
fg_color    = "#f6f8fa"
intensity   = "Normal"
underline   = "None"
italic      = true
strikethrough = false

[colors.tab_bar.new_tab]
bg_color    = "#515a65"
fg_color    = "#c0c5cb"
intensity   = "Normal"
underline   = "None"
italic      = true
strikethrough = false

[colors.tab_bar.new_tab_hover]
bg_color    = "#515a65"
fg_color    = "#f6f8fa"
intensity   = "Normal"
underline   = "None"
italic      = true
strikethrough = false