classic: false
blocks:
  - permission
  - user
  - group
  - size
  - name
date: '+%Y-%b-%d'
color:
  when: auto
  theme: custom
icons:
  when: never
  theme: fancy
  separator: " "
layout: grid
size: short
total-size: false
permission: rwx
sorting:
  # Possible values: extension, name, time, size, version
  column: name
  reverse: false
  # Possible values: first, last, none
  dir-grouping: first
symlink-arrow: ⇒
