shell = "zsh -c '{}'"

[[items]]
file = "$XDG_CONFIG_HOME/sway/theme"
template = "sway"
subtemplate = "colors_extra"
hook = "swaymsg reload"
# Swaymsg reload temporarily freezes input, so it's marked as not light
light = false

[[items]]
file = "$ZDOTDIR/base16_theme.sh"
template = "shell"
rewrite = true
hook = "$ZDOTDIR/base16_theme.sh"

[[items]]
file = "$XDG_CONFIG_HOME/foot/colors.ini"
template = "foot"
rewrite = true

[[items]]
file = "$XDG_CONFIG_HOME/kitty/colors.conf"
template = "kitty"
rewrite = true

[[items]]
file = "$XDG_CONFIG_HOME/wezterm/base16.toml"
template = "wezterm"
subtemplate = "extra"
rewrite = true

[[items]]
file = "$XDG_CONFIG_HOME/nvim/lua/custom/plugins/mini.lua"
template = "nvim"
rewrite = false
start = "-- Start flavours"
end = "-- End flavours"

[[items]]
file = "$XDG_CONFIG_HOME/lsd/colors.yaml"
template = "lsd"
rewrite = true

[[items]]
file = "$XDG_CONFIG_HOME/cava/config"
template = "cava"
