shell = "zsh -c '{}'"

[[items]]
file = "$XDG_CONFIG_HOME/sway/colorscheme"
template = "sway"
subtemplate = "colors"
hook = "swaymsg reload"
# Swaymsg reload temporarily freezes input, so it's marked as not light
light = false

[[items]]
file = "$ZDOTDIR/base16_theme.sh"
template = "shell"
rewrite = true
hook = "$ZDOTDIR/base16_theme.sh"

[[items]]
file = "$XDG_CONFIG_HOME/foot/colors.ini"
template = "foot"
rewrite = true

[[items]]
file = "$XDG_CONFIG_HOME/nvim/lua/emma/colors.lua"
template = "neovim"
rewrite = true

[[items]]
file = "$XDG_CONFIG_HOME/lsd/colors.yaml"
template = "lsd"
rewrite = true
