select = [
    "E",
    "F",
]

extend-select = [
    "I",    # isort

    # Flake8
    "ARG",  # unused-arguments
    "COM",  # commas
    "DTZ",  # datetimez
    "EM",   # errmsg
    "EXE",  # executable
    "ISC",  # implicit-str-concat
]
